services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    volumes:
      - ./otel/otel-config.yaml:/etc/otel/config.yaml
    command: [ "--config=/etc/otel/config.yaml" ]
    ports:
      - "9464:9464" # for Prometheus
      - "4317:4317" # for Gnoland
    networks:
      - monitoring

  validator1:
    image: gnoland-image:latest
    container_name: validator1
    volumes:
      - ./Validateur/gnoland-data:/gnoroot/gnoland-data/:rw
      - ./Validateur/genesis.json:/gnoroot/genesis.json
    ports:
      - "26656:26656" # P2P
      - "26657:26657" # RPC
      - "26660:26660" # Metrics (si activé dans Gnoland)
    #command: [ "gnoland", "start", "--lazy" ]
    command: [ "gnoland", "start", "config", "/gnoroot/gnoland-data/config/config.toml" ]
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge
