services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    volumes:
      - ./otel/otel-config.yaml:/etc/otel/config.yaml
    command: [ "--config=/etc/otel/config.yaml" ]
    ports:
      - "9464:9464" # for Prometheus
      - "4317:4317" # for Gnoland
    networks:
      - monitoring

  block-exporter:
    image: block_exporter
    container_name: block-exporter
    ports:
      - "8080:8080" # Port pour l’export des métriques
    networks:
      - monitoring
    command: [ "go", "run", "block_exporter.go" ]

  validator1:
    image: gnoland-image:latest
    container_name: validator1
    volumes:
      - ./initvalidator.sh:/gnoroot/initvalidator.sh
      - ./Validateur/config.toml:/gnoroot/gnoland-data/config/config.toml
    ports:
      - "26656:26656" # P2P
      - "26657:26657" # RPC
      - "26660:26660" # Metrics (si activé dans Gnoland)
    #command: [ "gnoland", "start", "--lazy" ]
    #command: [ "gnoland", "start", "config", "/gnoroot/gnoland-data/config/config.toml" ]
    entrypoint: [ "sh", "/gnoroot/initvalidator.sh" ]
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge
