interval_seconde: 1200
backend_port: "8989"
allow_origin: "http://gnomonitoring-frontend:3000"
rpc_endpoint: "https://test7.onbloc.xyz"
windows_size: 100
daily_report_hour: 16
daily_report_minute: 58
metrics_port: 8888
gnoweb: "https://gnoweb.test7.testnets.gno.land"
