services:
  detect-proposal:
    build: .
    restart: on-failure
    container_name: detect-proposal
    volumes:
      - ./main.go:/root/main.go
      - ./config.yaml:/root/config.yaml
      - ./go.mod:/root/go.mod
      - ./go.sum:/root/go.sum
    command: [ "go", "run", "main.go" ]
