global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:9464']

  - job_name: "node_exporter"
    static_configs:
      - targets: ["localhost:9100"]
