rpc_endpoint: "https://rpc.test6.testnets.gno.land"
discord_webhook_url : "https://discord.com/api/webhooks/1362423744097681458/vslQMyePTF587NZzwD979Q_p8b3xtmlUrKR154liHoGSxTWbILh7Lf4-_Y75W0TFPTV5"
windows_size : 100
daily_report_hour: 16    
daily_report_minute: 0
metrics_port: 8888