services:
  moni-goland:
    image: moni-gnoland
    restart: on-failure
    container_name: moni-goland
    volumes:
      #   - ./moniGnoland.go:/root/moniGnoland.go
      - ./config.yaml:/root/config.yaml
    #   - ./go.mod:/root/go.mod
    #   - ./go.sum:/root/go.sum
    ports:
      - 8888:8888
    # command: [ "go", "run", "main.go" ]
