services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gnomonitoring_frontend
    ports:
      - "9090:3000"
    volumes:
      - .env.local:/app/.env.local
    env_file:
      - .env.local
    restart: unless-stopped